MS-1 Team page
protyagov/martspec pull request #18
Opened 2023-01-04 12:39 UTC by stochna

2023-01-05 02:33 UTC, protyagov requested changes

2023-01-05 02:33 UTC, protyagov commented on src/sass/base.scss
> +        font-size: 3rem;
<img width="1713" alt="Screen Shot 2023-01-04 at 19 03 21" src="https://user-images.githubusercontent.com/7088732/210678579-ce563933-07f7-4dab-894f-086eb25f8d9a.png">

2023-01-05 07:42 UTC, stochna commented on src/sass/base.scss
> +        font-size: 3rem;
Понимаю, делала это исходя из макета. Там h1 на вех стр именно такой - 32px, что для нас равняется +- 3 rem (так как font-size на html установлен 13px). Коммит именовала соответствующе. Откатить это изменение?

2023-01-05 07:42 UTC, stochna commented on src/sass/base.scss
> +        font-size: 3rem;
![Desktop - 5](https://user-images.githubusercontent.com/53754381/210727464-b366e9ac-8c4c-451a-ba7c-05fa0c4d8166.png)

2023-01-05 07:43 UTC, stochna commented on src/sass/base.scss
> +        font-size: 3rem;
![Desktop - 5](https://user-images.githubusercontent.com/53754381/210727518-78f0e2b7-d4c5-4342-bcb7-9a9a3ff569cc.png)

2023-01-06 04:30 UTC, protyagov requested changes
Lets fix Our Team link in the footer and we should be good to go.

2023-01-06 18:40 UTC, protyagov approved these changes
lets merge to main and deploy

2023-01-06 19:41 UTC, merged