fix appleBtn
protyagov/martspec pull request #195
Opened 2023-11-21 21:29 UTC by NateSSaw

2023-11-21 21:34 UTC, protyagov requested changes

2023-11-21 21:34 UTC, protyagov commented on src/atomic/molecule/page-header.tsx
> +import ButtonApple from "../atom/buttonApple";
А давайте на src/atomic/atom/button-appple поменяем. 

Файл тоже двайте через тире тк все остальные тире используют вместо cammelCase

2023-11-21 21:34 UTC, protyagov commented on src/atomic/molecule/page-header.tsx
> +import ButtonApple from "../atom/buttonApple";
src кстати это алиас, хотя не самое лучшее имя, думаю в Slack надо обсудить.

2023-11-22 08:42 UTC, NateSSaw commented on src/atomic/molecule/page-header.tsx
> +import ButtonApple from "../atom/buttonApple";
хорошо

2023-11-28 07:45 UTC, merged