"Emotion" page fix; Metatags deleted
protyagov/martspec pull request #2
Opened 2022-09-05 03:06 UTC by nichitatrifan

2022-09-05 06:56 UTC, protyagov requested changes
Mostly good, we just need to remove ms-back class

2022-09-05 06:56 UTC, protyagov commented on src/sass/section.scss
>  .ms-back {
Delete this class completely.

2022-09-05 06:56 UTC, protyagov commented on src/landing/p7-emotion.tsx
>          <div className="ms-base-page pb-5 ms-back">
Class ms-back can be deleted, it is not used.

2022-09-06 01:20 UTC, nichitatrifan commented
deleted the 'ms-black' class

2022-09-06 01:20 UTC, merged