[MS-1051] ColorTest templates and sitemap
protyagov/martspec pull request #240
Opened 2023-12-05 19:04 UTC by stochna

2023-12-05 20:55 UTC, protyagov requested changes
В арабском файле написал что не так пошло, но это касается всех темплейтов. Надо будет создать отдельную историю для других страниц, я видимо пропустил это на каком-то этапе, сейчас посмотрел и похожие проблемы в Биоритмах и некоторых других страницах.

2023-12-05 20:55 UTC, protyagov commented on src/template/ar/emotion/color-test.ejs
> +    <link rel="alternate" hreflang="x-default" href="https://martspec.com/emotion/color-test" />
x-default - это страница, которую по умолчанию Гугл использует и показывает в результатах поиска. Для арабского это арабский URL.

https://developers.google.com/search/blog/2013/04/x-default-hreflang-for-international-pages

2023-12-05 20:55 UTC, protyagov commented on src/template/ar/emotion/color-test.ejs
> +    <link rel="alternate" hreflang="en" href="https://martspec.com/emotion/color-test" />
Эту линию можно удалить тк англ версия на линии 16 указана.

2023-12-06 11:07 UTC, stochna commented on src/template/ar/emotion/color-test.ejs
> +    <link rel="canonical" href="https://martspec.com/emotion/color-test" />
@protyagov поняла, исправила. На остальные файлы сделала [историю](https://martspec.atlassian.net/browse/MS-1070).

2023-12-06 16:55 UTC, protyagov requested changes
Нашел еще пару пунктов, только в секции Open Graph. На примере с арабским написал в каких линиях неточности. Остальные тоже надо поправить.

2023-12-06 16:55 UTC, protyagov commented on src/template/ar/emotion/color-test.ejs
> +    <meta property="og:locale" content="en_US" />
Для каждого языка своя кодировка должна быть. вчера не заметил, тут надо ar_SA. Можно посмотреть пример в странице витаминов или about.

2023-12-08 09:50 UTC, merged