MS-1139 Talia page style changed & translated into all languages
protyagov/martspec pull request #375
Opened 2024-02-27 12:07 UTC by IrinaShchetko

2024-02-27 13:56 UTC, winerar commented
В локализациях удалён ключ BTN_OPEN - он нужен для главной страницы, надо вернуть

2024-02-27 21:22 UTC, IrinaShchetko commented
> В локализациях удалён ключ BTN_OPEN - он нужен для главной страницы, надо вернуть

исправила

2024-02-29 05:46 UTC, protyagov requested changes
В целом все хорошо выглядит, но сломалась домашняя страница, если открыть дом страницу и прокрутить вниз, то изображение там нет. Я думаю из-за того, что вы удалили waist-home-XX.webp

2024-02-29 22:08 UTC, IrinaShchetko commented
исправила

2024-03-01 04:36 UTC, protyagov approved these changes
Please merge to master branch and deploy to the website

2024-03-02 13:57 UTC, merged