RU: Biorhythms page_Update ru.json
protyagov/martspec pull request #403
Opened 2024-03-11 12:28 UTC by EkaterinaSokolova-V

spelling mistakes

2024-03-11 13:34 UTC, winerar commented on src/i18n/ru.json
> +            "LI2_TEXT": "Нарушение биологического ритма вызывает расстройства сна такие, как бессонница.",
тут было правильно

2024-03-11 13:37 UTC, winerar requested changes
поправь строку 1084

2024-03-11 13:39 UTC, EkaterinaSokolova-V commented on src/i18n/ru.json
> +            "LI2_TEXT": "Нарушение биологического ритма вызывает расстройства сна такие, как бессонница.",
расстройство сна такое, как бессонница. либо
расстройства сна такие, как бессонница.
как надо?

2024-03-12 12:18 UTC, winerar approved these changes

2024-03-12 12:22 UTC, merged