new header component
protyagov/martspec pull request #467
Opened 2024-05-23 12:19 UTC by Ljoskold

Created new organism, 
adjusted responsiveness , 
added new LIST line for every languge on VITAMIN PAGE HEADER (according to the new design), 
added some images(not all new images were included on google.drive from designer, need to add later)

2024-05-23 15:36 UTC, protyagov requested changes

2024-05-23 15:36 UTC, protyagov commented on src/sass/page/base-new.scss
> +        @include media-breakpoint-down($base-breakpoint) {
а получится все изменения в этом файле не делать -- по атомарному дизайн желательно иметь компоненты самодостаточные. Тут мы должны знать, что для Хедера у нас стили в 2х местах находятся. если так все компоненты делать, то сложность проекта через пару месяцев увеличится.

2024-05-25 09:25 UTC, Ljoskold commented on src/atomic/organism/header.tsx
> +        <div className="ms-base-new">
Да

2024-05-25 10:19 UTC, Ljoskold commented
Я всё исправил, но теперь не знаю как уже обновленный файлы отправить сюда в PR 
Или нужно этот удалить, создать новый pr?

2024-05-26 14:31 UTC, protyagov approved these changes

2024-05-27 09:45 UTC, merged