[MS-1232] Tried to make a bullet-list component
protyagov/martspec pull request #483
Opened 2024-07-08 14:54 UTC by rtsedenova

Tried to make a bullet-list component

2024-07-08 16:54 UTC, protyagov requested changes
1. Пару коментов по импортам
2. А SVG иконку вы добавили как файл и видимо встроили как inline в bullet-list.tsx? Таким образом сам SVG не используется ? Тогда может удалить ?
3. Пока нет страницы карьер давайте применим этот компонент на странице Витамин. Только там надо учесть, что цвет синий, поэтому цвет должен через пропсы передаваться в компонент.
<img width="1605" alt="Screenshot 2024-07-08 at 11 54 08" src="https://github.com/protyagov/martspec/assets/7088732/c8e56ae6-cbc7-4140-bb29-42d5f03d91f2">

2024-07-08 16:54 UTC, protyagov commented on src/atomic/molecule/bullet-list.tsx
> +import '../../sass/molecule/bullet-list.scss';
Используйте  алиас вместо ..\..

2024-07-08 16:54 UTC, protyagov commented on src/sass/molecule/bullet-list.scss
> +@import "../atom/color.scss";
используйте алиас

2024-07-08 16:54 UTC, protyagov commented on src/sass/molecule/page-header.scss
> +@import "@/sass/atom/_base-new-vars";
?

2024-07-09 18:22 UTC, rtsedenova reviewed
• Used aliases in imports;
• Replaced <ul> list with a bullet-list component on vitamin page;
• Tried to change styles (remove unused ones and so on);
• Deleted svg yellow-check-mark;

2024-07-09 18:24 UTC, rtsedenova commented on src/sass/molecule/page-header.scss
> +@import "@/sass/atom/_base-new-vars";
Извиняюсь, ошиблась. Потом только прочитала, что это partial файл, который не будет компилироваться в css.

2024-07-09 18:45 UTC, protyagov approved these changes
Все хорошо. Теперь как в прошлый раз -- merge в master branch и уже с master branch делаем деплоймент на сайт.

2024-07-10 10:35 UTC, merged