[MS-535] change meta descriptions for en pages
protyagov/martspec pull request #486
Opened 2024-07-12 18:34 UTC by EGRrqq

changed og:description for about and team pages

2024-07-12 18:41 UTC, protyagov requested changes
Закрывающий слеш не нужен на тагах типа VOID (meta, link) и тп

https://developer.mozilla.org/en-US/docs/Glossary/Void_element

2024-07-12 19:09 UTC, EGRrqq commented
Prettier автоматом ставит закрытые слеши везде. Я могу в конфиге для vscode поменять, [вот так](https://stackoverflow.com/questions/65105287/how-to-stop-prettier-from-using-the-old-self-closing-tag-syntax)

Просто в других файлах, они рандомно стоят. Вот скриншот bodyzinc, японский язык.
![image](https://github.com/user-attachments/assets/0ce580c5-3d2e-4f94-bce8-a12dff8e9609)
тут у meta тега то есть, то нет слеша

2024-07-12 19:10 UTC, EGRrqq commented
я могу поменять свой конфиг и прогнать prettier для template папки

2024-07-12 19:17 UTC, EGRrqq commented
а нет, я не могу таким способом прогнать prettier. Prettier не как не зависит, от vscode конфига.

я вот нашел ветку обсуждения у mdn связанную с этим
https://github.com/orgs/mdn/discussions/242

2024-07-16 06:52 UTC, EGRrqq commented
я сделал revert и заново сделал коммит без новых слешей.

еще удалил пустой файл, который проник в одном из прошлых коммитов

2024-07-16 06:53 UTC, winerar commented
@EGRrqq Prettier если будешь менять, то лучше сразу в конфиге репозитория, чтоб у всех было одинаково

2024-07-16 07:04 UTC, EGRrqq commented
> @EGRrqq Prettier если будешь менять, то лучше сразу в конфиге репозитория, чтоб у всех было одинаково

У prettier нет такой опции, к сожалению. 

Я поменял defaulFormatter в vscode, [вот так](https://stackoverflow.com/questions/65105287/how-to-stop-prettier-from-using-the-old-self-closing-tag-syntax)

Возможно получиться сделать чтобы это сохранилось в .vscode и запушить. Стоит попробовать, как минимум новых слешей это добавлять не будет, старые останутся

2024-07-16 07:13 UTC, EGRrqq commented
теперь эта опция у всех

2024-07-16 17:17 UTC, protyagov approved these changes

2024-07-16 17:17 UTC, merged