Ms 1245 new component prototype job page
protyagov/martspec pull request #495
Opened 2024-08-08 08:18 UTC by rtsedenova

PR - Job Page (For checking, lacks translations into several languages and banner component)

2024-08-08 18:18 UTC, protyagov requested changes
Комент по поводу index.tsx и изображения возможно лишние, в Слак написал.

2024-08-08 18:18 UTC, protyagov commented on src/index.tsx
> +root.render(<App />);
Это будет давать рендеринг страницы дважды как мне думается, поэтому лучше убрать. EventBus запскает при инициализации смену языка и это в свою очередь запускает рендеринг, поэтому еще раз его не надо на линии 13 запускать.

2024-08-09 20:32 UTC, rtsedenova reviewed
I made a mistake and didn't add style import for the job details page, so the styles weren't applied - this has been fixed

2024-08-09 20:54 UTC, rtsedenova reviewed
removed images and sh script

2024-08-12 15:33 UTC, protyagov approved these changes

2024-08-13 14:35 UTC, merged